### ISSUE TITLE
Write a self test script

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#32] opened 2019-09-01 09:17 UTC
Package all the unit hardware test we have into one script that could be played by user to detect hardware related issue regarding the PCB but also regarding the "rabbit" : speakers, button, volume, lineout and most importantly motors (some rabbit's owner mentionned dead motors : the code should adapt to this).

**Comment by pguyot** [comment] 2019-09-01 17:11
Dupe of #19

**Closed by pguyot** 2019-09-01 17:11 UTC
