### ISSUE TITLE
OSError: [Errno 14] Bad address after waking up

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#68] opened 2020-01-05 10:24 UTC
**Symptoms** : no animation, no sounds playing, violet led pulsing
**Information système AVANT et APRES reboot** :
Oreille gauche
    ok (position=0)
Oreille droite
    broken
**Information système APRES power off/on** :
Oreille gauche
    ok (position=0)
Oreille droite
    ok (position=9)

**Log** : 

DEBUG 2020-01-05 08:00:01,036 packet from service: {'type': 'wakeup'}
DEBUG 2020-01-05 08:00:01,319 do_go 0
DEBUG 2020-01-05 08:00:01,332 do_go 1
DEBUG 2020-01-05 08:00:01,337 _do_wait_while_running
DEBUG 2020-01-05 08:00:04,406 do_read from 1
ERROR 2020-01-05 08:00:04,409 ear 1 has been declared broken
DEBUG 2020-01-05 08:00:04,542 Traceback (most recent call last):
  File "/home/pi/pynab/nabd/nabd.py", line 539, in service_loop
    await self.process_packet(packet, writer)
  File "/home/pi/pynab/nabd/nabd.py", line 484, in process_packet
    await processors[packet["type"]](packet, writer)
  File "/home/pi/pynab/nabd/nabd.py", line 377, in process_wakeup_packet
    await self.transition_to_idle()
  File "/home/pi/pynab/nabd/nabd.py", line 259, in transition_to_idle
    await self.process_idle_item(item)
  File "/home/pi/pynab/nabd/nabd.py", line 181, in process_idle_item
    await self.set_state("idle")
  File "/home/pi/pynab/nabd/nabd.py", line 264, in set_state
    await self.idle_setup()
  File "/home/pi/pynab/nabd/nabd.py", line 117, in idle_setup
    await self.nabio.move_ears(self.ears["left"], self.ears["right"])
  File "/home/pi/pynab/nabd/nabio_hw.py", line 33, in move_ears
    await self.ears.wait_while_running()
  File "/home/pi/pynab/nabd/ears_dev.py", line 117, in wait_while_running
    self.executor, self._do_wait_while_running
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/pynab/nabd/ears_dev.py", line 130, in _do_wait_while_running
    os.write(self.fds[1], b".")
OSError: [Errno 14] Bad address

**Comment by pguyot** [comment] 2020-01-05 10:37
Duplicate of https://github.com/pguyot/tagtagtag-ears/issues/1

**Closed by pguyot** 2020-01-05 10:37 UTC
Labels: bug
